### ISSUE TITLE
app-office/drawio-desktop-bin: [RFE] add symlink to the executable

### ISSUE THREAD

**Issue by sphakka** [SpiderX/portage-overlay#13]
Thanks for this ebuild :-)

The executable is installed as `/opt/draw.io/drawio` which is not in env `PATH`: I had to `equery f ...` to find it out. Could you please enhance it with a symlink

    /usr/local/bin/drawio -> /opt/draw.io/drawio

or print a post-inst message instructing to update user's `PATH`?

**Comment by SpiderX** [comment]
@sphakka You're welcome.
Symlink in /usr/local/bin/drawio is not a good idea, since /usr/local is place where something local to specific system should go or/and user files. Files installed by portage are not "user" and is not "local".
Actually symlink to any places that are in PATH by default will be pointless, because the only reason for such symlink existence is its presents in a PATH by default.
Instead ebuild will add /opt/draw.io/drawio to PATH.
To get it in current shell env-update && source /etc/profile after ebuild emerge.
