### ISSUE TITLE
dev-db/mssql-scripter: No usable version of the libssl was found

### ISSUE THREAD

**Issue by 3NdR1m** [SpiderX/portage-overlay#32]
Missing dependencies perhaps? I think mssql needs dev-libs/openssl:1.0.0.

**Comment by SpiderX** [comment]
@3NdR1m Not really.

The problem is in package itself. It relies on old version [microsoft/sqltoolsservice](https://github.com/microsoft/sqltoolsservice). that has been built against old version of openssl. I replaced sqltoolsservice with the recent version, but some part of this package has been built against openssl 1.0.1, which doesn't exist in portage anymore.

Anyway, I tried to connect to some mssql server and got and error:

`System.Security.Authentication.AuthenticationException: The remote certificate was rejected by the provided RemoteCertificateValidationCallback`

which is expected in my case due to [this](https://github.com/dotnet/SqlClient/issues/1402).

So, mssql-scripter has found some SSL, so you can try once again.

P.S. Maybe there will be a need to emerge dev-libs/openssl-compat, but I don't see any evidence of that right now, and therefore openssl-compat is not in dependencies.
